[package]
name = "nlp_stuff"
version = "0.1.0"
authors = ["Steven <steven@pelotoncycle.com>"]

[dependencies]
itertools = "0.5.5"
rayon = "0.5.0"
lazy_static = "0.1.*"
regex = "0.1"
rustc-serialize = "0.3"
